version: "3.8"
services:
  backend:
    build: ./greenheat-backend
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ./greenheat-frontend
      args:
        ENVIRONMENT: docker
    ports:
      - "4200:4200"